# Generated by Django 3.2.6 on 2023-12-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvalue',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
