# Generated by Django 3.2.6 on 2023-12-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_purchaselist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
